### ISSUE TITLE
how to destory numerous nav instances? 

### ISSUE THREAD

**Issue by xulong3370** [zyra/ionic-super-tabs#104]
I see each slider or change tab create a new navcontroller instance...

When there are lots of tab views, I want to destory one of them, I use navCtrl.pop() comes error...

Becase each tab has unique navController instance, and nav.length = 1. It can not dismiss!

**Comment by ihadeed** [comment]
You should destroy the root NavController. The one that holds the `super-tabs` component.

**Comment by xulong3370** [comment]
@ihadeed  Hi! I don't want to destroy the root nav. The new view will be loaded or created when I slide to the new tab, but I want to unload or destroy the view of invisible tabs...

**Comment by ihadeed** [comment]
So what you're asking for is to unload the tabs if it's not possible for the user to swipe into them? 

Example, if you have 4 tabs:
- the component only loads tab 1 + 2
- if you swipe to tab 2, tab 3 will be loaded in case the user swipes into it
- if you swipe to tab 3, tab 1 will be unloaded because the user can't swipe into it anymore, tab 4 will be loaded

So basically only keep 3 tabs loaded at a time?

**Comment by xulong3370** [comment]
@ihadeed YES! That's what I mean ! just keep 3 tabs loaded at  a time. Forgive my limited ability to express! Is there a function to solve this issue ?

**Comment by ihadeed** [comment]
Not at the moment, I'll add it in future releases.

**Comment by xulong3370** [comment]
@ihadeed     I got it....  Thanks a lot!
