### ISSUE TITLE
swipeBackEnabled not work

### ISSUE THREAD

**Issue by longdw** [zyra/ionic-super-tabs#150]
`<ion-nav [root]="rootPage" #content swipeBackEnabled="true"></ion-nav>`
in other page I can swipe to back, but in super-tabs page swipe-back not work.

**Comment by ihadeed** [comment]
Looks like I'm able to swipe to go back when pushing a view inside a super-tab .. but not when pushing using `rootNavCtrl`

**Comment by sourbell** [comment]
Facing the same problem, as @ihadeed mentioned above, `swipeBackEnabled` will not work if i use `rootNavCtrl`, i'm wondering if there's some workaround, or if you have any plan to solve this problem, many thanks :) 

Great project!

**Comment by aboduo** [comment]
@ihadeed   @sourbell After some difficult digging,  I think I found the root cause. But I don't why. 

Please refer to the function `canSwipeBack` of  `nav-controller-base.js`.

![untitled 2](https://user-images.githubusercontent.com/3221330/37289419-981466c0-2644-11e8-8803-c0130c15bc21.png)

Because the `_children` of `Tab` has a item `SuperTabs`, so the `canSwipeBack` return false. If we remove the line 917 (`!this._children.length &&`), then swipe back works fine.

**Comment by AG914** [comment]
I have remove the line 917 but not work, the swipe back don't work with rootNavCtrl.
