### ISSUE TITLE
ionic super tabs bug

### ISSUE THREAD

**Issue by Caturix2199** [zyra/ionic-super-tabs#269]
I watched several YT videos or posts in forums about super-tabs and did it exactly like it was shown. But somehow it is not working:( Do you have a solution or is super-tabs just not working anymore? (I created a default tabs project to show you this problem. So its a default ionic tabs project. Nothing is changed except the code I post here . So when I change the super-tabs back to ion-tabs, Everything is normal. That’s the reason why I thought it has to be a bug.)
<img width="296" alt="bildschirmfoto 2018-02-15 um 16 41 34" src="https://user-images.githubusercontent.com/32932656/36273498-f93be4f6-1284-11e8-9c3c-733d6bac0ae2.png"> 

```
app.module.ts

import { SuperTabsModule } from "ionic2-super-tabs";
...
 imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    SuperTabsModule.forRoot(),

  ],

tabs.html

<super-tabs>
  <super-tab [root]="tab1Root" title="Home" icon="home"></super-tab>
  <super-tab [root]="tab2Root" title="About" icon="information-circle"></super-tab>
  <super-tab [root]="tab3Root" title="Contact" icon="contacts"></super-tab>
</super-tabs>

```

**Comment by eduardoRoth** [comment]
@Caturix2199 are you using IonicPage lazyloading? If that's the case, you also need to add `SuperTabsModule` in your ionic page module.

**example-tabs.module.ts**

```
import {
    NgModule
} from '@angular/core';
import {
    IonicPageModule
} from 'ionic-angular';
import {
    ExampleTabsPage
} from './example-tabs';
import {
    SuperTabsModule
} from 'ionic2-super-tabs';

@NgModule({
    declarations: [
        ExampleTabsPage,
    ],
    imports: [
        IonicPageModule.forChild(ExampleTabsPage),
        SuperTabsModule
    ],
})
export class ExampleTabsPageModule {}
```

**Comment by tushar-69** [comment]
tried SuperTabsModule imports but still doesnot work

**Comment by tushar-69** [comment]
This is what i get when i run it on browser

Uncaught Error: Template parse errors:
Can't bind to 'tabRoot' since it isn't a known property of 'super-tab'.
1. If 'super-tab' is an Angular component and it has 'tabRoot' input, then verify that it is part of this module.
2. If 'super-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <super-tabs height="100%">

  <super-tab [ERROR ->][tabRoot]="tab1Root" title="Home"></super-tab>

  <super-tab [tabRoot]="tab2Root" title="About"></sup"): ng:///AppModule/BeginPage.html@20:13
Can't bind to 'tabRoot' since it isn't a known property of 'super-tab'.
1. If 'super-tab' is an Angular component and it has 'tabRoot' input, then verify that it is part of this module.
2. If 'super-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <super-tab [tabRoot]="tab1Root" title="Home"></super-tab>

  <super-tab [ERROR ->][tabRoot]="tab2Root" title="About"></super-tab>

  <super-tab [tabRoot]="tab3Root" title="Contact"></"): ng:///AppModule/BeginPage.html@22:13
Can't bind to 'tabRoot' since it isn't a known property of 'super-tab'.
1. If 'super-tab' is an Angular component and it has 'tabRoot' input, then verify that it is part of this module.
2. If 'super-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <super-tab [tabRoot]="tab2Root" title="About"></super-tab>

  <super-tab [ERROR ->][tabRoot]="tab3Root" title="Contact"></super-tab>

</super-tabs>
"): ng:///AppModule/BeginPage.html@24:13
    at syntaxError (compiler.js:466)
    at TemplateParser.parse (compiler.js:24329)
    at JitCompiler._parseTemplate (compiler.js:33757)
    at JitCompiler._compileTemplate (compiler.js:33732)
    at compiler.js:33634
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:33634)
    at compiler.js:33504
    at Object.then (compiler.js:455)
    at JitCompiler._compileModuleAndComponents (compiler.js:33503)

**Comment by eduardoRoth** [comment]
@Caturix2199 `SuperTabs` doesn't use the attribute `tabRoot` it uses `root`:

**Quick Example** *(from the docs)*
```
<super-tabs>
  <super-tab [root]="page1" title="First page"></super-tab>
  <super-tab [root]="page2" title="Second page"></super-tab>
  <super-tab [root]="page3" title="Third page"></super-tab>
</super-tabs>
```

Change that and it'll work.

**Comment by saihanuman73** [comment]
Im getting getActiveChildNavs Error Some one pls help me out

**Comment by vibinflogesoft** [comment]
Hi@saihanuman73 
Iam facing the issue .Did you get any solution for this?
Please let me know if you have any solution for this

**Comment by saihanuman73** [comment]
No @vibinflogesoft , Didn't get any solution. I'm now using Ionic Tabs, Instead of supertabs

**Comment by ManoMahe** [comment]
I think this issue is still not rectified? can  you please help me in this case?
