### ISSUE TITLE
How to trigger ionViewDidEnter() on tab4, when i come back from another page to my supertabs page

### ISSUE THREAD

**Issue by jessicastorm1986** [zyra/ionic-super-tabs#311]
Brief Explanation: I used supertabs in homepage and created 4 tabs. By using rootnavcontroller, I navigate to another page. When i come back to homepage (it by default lands on 4th tab from where i navigated) and I want to call ionViewDidEnter() of the page called in 4th tab.

How do i do this ?  Please help.

**Comment by jessicastorm1986** [comment]
Any help expected ??

**Comment by aleygues** [comment]
Hi, I'm facing the same situation, here is my solution:

Instead of trying to trigger `ionViewDidEnter()` on your superTab, you can simply use the `ionViewDidLeave()` (or willLeave) method of the view you are coming back from!

Then there are 2 cases: 
* the action you want to perform concern a sevice: you can simply call the same service from the other page
* the action you want to perform concern the superTab component: you have to find a way to get notified by the other view `ionViewDidLeave` method (a solution could be to pass a Promise as a param to this view, and to resolve the promise when `ionViewDidLeave` is called).

I can provide you a demo if needed!
