### ISSUE TITLE
View not updated

### ISSUE THREAD

**Issue by karuppasami6492** [zyra/ionic-super-tabs#336]
when back from child page to super tabs page view not updated

**Comment by TomCosta** [comment]
Me too... If I have a new data in the arrays, the view shows the old data. Some tips?

**Comment by eduardoRoth** [comment]
Are you loading data in the `ionViewWillLoad` or `ionViewDidLoad`? Because if that's so, the event only fire once when SuperTabs load the page.

If you want to always load data when entering the page, then use `ionViewWillEnter` o `ionViewDidEnter`, or use sockets to update data in real time or a custom event
