### ISSUE TITLE
Swipe/Drag event

### ISSUE THREAD

**Issue by Adenon** [zyra/ionic-super-tabs#347]
Hii, Iam using ion refresher in every tab in super-tabs, and when dragging left or right to swipe between tabs, the pull for refresh steel be enable, so I was wandering if an event of swipe or drag exist in super tabs so I can diseable and enable the refresh when I do the swipe.
Thank you

**Comment by lincolnthree** [comment]
I think you're looking for this. For some reason I guess the PR I got this from never got merged... probably because it had some extra stuff in it that didn't get cleaned up. The requester closed it.

https://github.com/zyra/ionic2-super-tabs/pull/166/commits/9d36d0e23eff28b13c12993f9e76756aaa6d7956
