### ISSUE TITLE
Is it possible to do nested tabs?

### ISSUE THREAD

**Issue by aditbharadwaj** [zyra/ionic-super-tabs#396]
Well iam using super tabs as base navigation  but as u can see in this pic i place two more tabs inside one ? and their routing component is different but when i press the inside tabs they navigate to the main app tab navigation why is that ? the page is navigated to the called page but it also takes me to home page of my base navigation
![123](https://user-images.githubusercontent.com/6751554/67157397-01362a80-f349-11e9-9f46-2189b87de73c.PNG)

**Comment by ihadeed** [comment]
This is probably due to the `querySelectorAll` calls that super tabs uses. The selectors aren't restricted to direct children and they're picking up events from the nested tabs.

Generally speaking having nested tabs isn't a good idea since it can confuse both the user and the web view. There shouldn't be more than one element that can be swiped. Consider using normal tabs for one of the views and super tabs for the other.

**Comment by aditbharadwaj** [comment]
Well this issue is close but i found a way to do nested tabs but also making use of super tabs , i used **ion-segment and *ngif** to make a nested tab inside the super tab component loaded and it works flawlessly .

Just updating this thread may it help some one in future.
