### ISSUE TITLE
TypeError: Cannot read property 'getActiveChildNavs' of undefined

### ISSUE THREAD

**Issue by beingakashyadav** [zyra/ionic-super-tabs#419]
then i get this error

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getActiveChildNavs' of undefined
TypeError: Cannot read property 'getActiveChildNavs' of undefined

**Comment by ihadeed** [comment]
1. When are you calling `addPage` ?
2. Do you have full stack trace?

From the info you provided my best guess is that you're calling `addPage` too soon while the page is still loading. Possibly an Ionic Framework component has indexed all the present `ion-nav` and is looping through them and since you modified the array some of them were undefined. This kind of issue is typically resolved by doing one of the following:
- delay any DOM or variable modifications until a bit after the page initialization
- use Angular's built in tracking (`trackBy`); which is always a good thing to do in `ngFor` loops that have dynamic data

**Comment by beingakashyadav** [comment]
1. i call addPage after all page loaded coz i receive data from api then it load in html and manual clicked at addPage to add new page in tabs.. manual click i delay 2,3 min to call addPage but also not working.

2. No i dont use full stack trace.

**Comment by beingakashyadav** [comment]
New Tab wil load but tab page wil not be load. this error  will be seen in console Uncaught (in promise): TypeError: Cannot read property 'getActiveChildNavs' of undefined...

**Comment by beingakashyadav** [comment]
i used full stack trace and its detect new tabs index but. tab page load still error and swipe dont work in dynamic added tabs. please check it.

**Comment by ihadeed** [comment]
I meant if you could share the full error stack trace that would help me figure out the issue.

A minimal project that has this issue also helps so I can take a look locally.

A few things to try on your end:
- Use `trackBy` in your `ngFor` usage. https://medium.com/better-programming/improving-angular-ngfor-performance-through-trackby-ae4cf943b878
- If you are calling `addPage` in `ngOnInit` or the class constructor, try moving to `ngAfterViewInit` or set a delay using `setTimeout` to see if it helps.

**Comment by beingakashyadav** [comment]
this is project how i add page which getting issue please check it. https://gitlab.com/me.punk.7/super-tabs.git
